import { Component, computed, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { forkJoin, map, switchMap } from 'rxjs';
import { Difficulty } from '@exams-generator/shared';
import { LucideAngularModule, Sparkles, TriangleAlert, Lock, Inbox, ChevronDown, ChevronRight } from 'lucide-angular';
import { ButtonComponent } from '../../../ui/button/button.component';
import { CardComponent } from '../../../ui/card/card.component';
import { EmptyStateComponent } from '../../../ui/empty-state/empty-state.component';
import { InputComponent } from '../../../ui/input/input.component';
import { ProgressComponent } from '../../../ui/progress/progress.component';
import { SelectComponent } from '../../../ui/select/select.component';
import { TableComponent } from '../../../ui/table/table.component';
import { TagComponent } from '../../../ui/tag/tag.component';
import { TaxonomyService } from '../../taxonomy/taxonomy.service';
import { Course } from '../../taxonomy/taxonomy.models';
import { ExamVersionsService } from '../../exam-versions/exam-versions.service';
import { ExamsService } from '../exams.service';
import {
  CreateExamBlueprintRow,
  GRADE_LEVELS,
  GRADE_LEVEL_LABELS,
  GradeLevel,
  StockBatchCellPayload,
} from '../exams.models';
import { CellKey, CellStatus, ContentRow, ExamBuilderStore, buildCellKey } from './exam-builder.store';

/** "Forma A/B" — the default number of versions generated by "Generar versiones" from this screen (design doc §5). */
const DEFAULT_VERSION_COUNT = 2;

const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  [Difficulty.Easy]: 'Fácil',
  [Difficulty.Medium]: 'Media',
  [Difficulty.Hard]: 'Difícil',
};

function parseCellKey(key: CellKey): { courseId: string; topicId: string; difficulty: Difficulty } {
  const [courseId, topicId, difficulty] = key.split(':') as [string, string, Difficulty];
  return { courseId, topicId, difficulty };
}

/** Toggle a course id's membership in the collapsed set (immutable copy — signal-friendly). */
function toggleInSet(current: ReadonlySet<string>, id: string): ReadonlySet<string> {
  const next = new Set(current);
  if (next.has(id)) {
    next.delete(id);
  } else {
    next.add(id);
  }
  return next;
}

/** One course's contiguous run of `ContentRow`s — powers the course subheading grouping (design doc §5.1's "árbol"). */
interface RowGroup {
  readonly courseId: string;
  readonly courseName: string;
  readonly rows: readonly ContentRow[];
}

/** Groups rows by course, preserving arrival order — `store.rows()` is already course-then-topic ordered (see `loadTopicsAndStock`). */
function groupRowsByCourse(rows: readonly ContentRow[]): readonly RowGroup[] {
  const groups: { courseId: string; courseName: string; rows: ContentRow[] }[] = [];
  for (const row of rows) {
    const lastGroup = groups[groups.length - 1];
    if (lastGroup && lastGroup.courseId === row.courseId) {
      lastGroup.rows.push(row);
    } else {
      groups.push({ courseId: row.courseId, courseName: row.courseName, rows: [row] });
    }
  }
  return groups;
}

/**
 * Master "tabla + preview vivo" exam-builder screen (design doc §5,
 * DECISION FE-5). Replaces `ExamCreateComponent` at `/app/exams`.
 *
 * The content grid auto-populates from the tenant's full course x topic
 * catalog (`TaxonomyService`) for the selected grade level — no manual
 * "add row" step, matching the design doc's fixed matrix. `ExamBuilderStore`
 * is provided HERE (component-scoped, not root) so state resets whenever
 * the user navigates away and back (DECISION FE-5).
 */
@Component({
  selector: 'app-exam-builder',
  standalone: true,
  // `<lucide-icon>` is used directly in this component's own template
  // (sparkles/triangle-alert/lock) AND inside the nested `ui-empty-state`
  // (inbox), so the bare module goes in `imports` (selector resolution) and
  // the icon providers go in `providers` — `.pick()`'s `ModuleWithProviders`
  // cannot go in `imports` (NG2012).
  imports: [
    ButtonComponent,
    CardComponent,
    EmptyStateComponent,
    InputComponent,
    LucideAngularModule,
    ProgressComponent,
    SelectComponent,
    TableComponent,
    TagComponent,
  ],
  providers: [
    ExamBuilderStore,
    LucideAngularModule.pick({ Sparkles, TriangleAlert, Lock, Inbox, ChevronDown, ChevronRight }).providers ?? [],
  ],
  templateUrl: './exam-builder.component.html',
})
export class ExamBuilderComponent {
  private readonly taxonomyService = inject(TaxonomyService);
  private readonly examsService = inject(ExamsService);
  private readonly examVersionsService = inject(ExamVersionsService);
  private readonly router = inject(Router);

  protected readonly store = inject(ExamBuilderStore);

  protected readonly difficulties: readonly Difficulty[] = [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard];
  protected readonly difficultyLabels = DIFFICULTY_LABELS;
  protected readonly gradeLevelOptions = GRADE_LEVELS.map((gradeLevel) => ({
    value: gradeLevel,
    label: GRADE_LEVEL_LABELS[gradeLevel],
  }));

  protected readonly selectedGradeLevel = signal<GradeLevel | null>(null);
  private readonly courses = signal<Course[]>([]);

  protected readonly loading = signal(false);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly emptyBank = signal(false);

  protected readonly loadingPreview = signal(false);
  protected readonly previewError = signal<string | null>(null);

  protected readonly generating = signal(false);
  protected readonly generateError = signal<string | null>(null);

  /** Rows grouped by course, for the "read like the tree" course subheading (design doc §5.1). */
  protected readonly groupedRows = computed<readonly RowGroup[]>(() => groupRowsByCourse(this.store.rows()));

  /**
   * Courses the user has manually collapsed. Default-empty means every course
   * starts EXPANDED (the grid is a fill-in matrix — hiding rows by default would
   * bury the work). Collapse is opt-in, to fold away courses the teacher isn't
   * touching. Mirrors the bank tree's `expand/collapse` affordance (commit 50dcff5).
   */
  private readonly collapsedCourses = signal<ReadonlySet<string>>(new Set());

  protected toggleCourse(courseId: string): void {
    this.collapsedCourses.update((current) => toggleInSet(current, courseId));
  }

  protected isCourseExpanded(courseId: string): boolean {
    return !this.collapsedCourses().has(courseId);
  }

  protected expandAll(): void {
    this.collapsedCourses.set(new Set());
  }

  protected collapseAll(): void {
    this.collapsedCourses.set(new Set(this.groupedRows().map((group) => group.courseId)));
  }

  protected chevronFor(expanded: boolean): string {
    return expanded ? 'chevron-down' : 'chevron-right';
  }

  protected onGradeLevelChange(gradeLevel: GradeLevel | null): void {
    this.selectedGradeLevel.set(gradeLevel);
    if (!gradeLevel) {
      return;
    }
    this.buildGrid(gradeLevel);
  }

  private buildGrid(gradeLevel: GradeLevel): void {
    this.loading.set(true);
    this.errorMessage.set(null);
    this.emptyBank.set(false);
    this.store.setGradeLevel(gradeLevel);

    this.taxonomyService.getCourses(gradeLevel).subscribe({
      next: (courses) => {
        this.courses.set(courses);
        if (courses.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }
        this.loadTopicsAndStock(gradeLevel, courses);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  private loadTopicsAndStock(gradeLevel: GradeLevel, courses: readonly Course[]): void {
    forkJoin(
      courses.map((course) =>
        this.taxonomyService
          .getTopics(course.id, gradeLevel)
          .pipe(map((topics) => topics.map((topic) => ({ course, topic })))),
      ),
    ).subscribe({
      next: (grouped) => {
        const pairs = grouped.flat();
        if (pairs.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }
        for (const { course, topic } of pairs) {
          this.store.addRow({
            id: `${course.id}:${topic.id}`,
            courseId: course.id,
            courseName: course.name,
            topicId: topic.id,
            topicName: topic.name,
          });
        }
        this.loadStock(gradeLevel);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  private loadStock(gradeLevel: GradeLevel): void {
    const cells: StockBatchCellPayload[] = [];
    for (const row of this.store.rows()) {
      for (const difficulty of this.difficulties) {
        cells.push({ courseId: row.courseId, topicId: row.topicId, difficulty });
      }
    }

    this.examsService.stockBatch({ gradeLevel, cells }).subscribe({
      next: (result) => {
        this.store.setStockResults(result.results);
        this.loading.set(false);
        const total = result.results.reduce((sum, cell) => sum + cell.available, 0);
        this.emptyBank.set(total === 0);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  protected cellKey(row: ContentRow, difficulty: Difficulty): CellKey {
    return buildCellKey(row.courseId, row.topicId, difficulty);
  }

  protected stockFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.stock().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.requested().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedStrFor(row: ContentRow, difficulty: Difficulty): string {
    const value = this.requestedFor(row, difficulty);
    return value > 0 ? String(value) : '';
  }

  protected previewFor(row: ContentRow, difficulty: Difficulty): readonly string[] {
    return this.store.previewCache().get(this.cellKey(row, difficulty)) ?? [];
  }

  protected statusFor(row: ContentRow, difficulty: Difficulty): CellStatus {
    return this.store.cellStatus(this.cellKey(row, difficulty));
  }

  /** Cell wrapper classes — shortage cells get an unmissable warning-stock tint + border (improvement 3). */
  protected cellClasses(row: ContentRow, difficulty: Difficulty): string {
    const base = 'px-3 py-2 align-top transition-colors';
    return this.statusFor(row, difficulty) === 'short'
      ? `${base} rounded-field border border-warn-text bg-warn-bg`
      : base;
  }

  /** Muted (not alarming) styling for an untouched zero-stock "de 0" label vs. the normal "de N" (improvement 4). */
  protected stockOkClasses(row: ContentRow, difficulty: Difficulty): string {
    return this.stockFor(row, difficulty) === 0 ? 'text-sm text-n400' : 'text-sm text-n600';
  }

  /** Per-difficulty column total for the totals row/footer (improvement 2). */
  protected totalFor(difficulty: Difficulty): number {
    return this.store.totalsByDifficulty().get(difficulty) ?? 0;
  }

  /** Grand total across every requested cell (improvement 2). */
  protected grandTotalValue(): number {
    return this.store.grandTotal();
  }

  protected onRequestedChange(row: ContentRow, difficulty: Difficulty, rawValue: string): void {
    const key = this.cellKey(row, difficulty);
    const count = Number(rawValue) || 0;
    this.store.setRequested(key, count);
    if (count <= 0) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.loadingPreview.set(true);
    this.previewError.set(null);

    this.examsService
      .previewExam({
        gradeLevel,
        blueprint: [{ courseId: row.courseId, topicId: row.topicId, difficulty, count }],
      })
      .subscribe({
        next: (result) => {
          this.loadingPreview.set(false);
          const questionIds = result.selections[0]?.questionIds ?? [];
          this.store.mergePreview(key, questionIds);
        },
        error: () => {
          this.loadingPreview.set(false);
          this.previewError.set('No se pudo cargar la vista previa. Inténtalo de nuevo.');
        },
      });
  }

  protected lowerToStock(row: ContentRow, difficulty: Difficulty): void {
    const stock = this.stockFor(row, difficulty);
    this.onRequestedChange(row, difficulty, String(stock));
  }

  protected goToUpload(): void {
    this.router.navigate(['/app/bank/upload']);
  }

  /**
   * Bridge to the AI generator. When launched from a specific shortage cell we
   * carry its curso·tema·dificultad·grado as query params so the generator opens
   * pre-filled — the teacher shouldn't re-pick what they already chose here. From
   * the empty-state button (no row) we still carry the selected grade.
   */
  protected goToAiGenerate(row?: ContentRow, difficulty?: Difficulty): void {
    const gradeLevel = this.selectedGradeLevel();
    const queryParams = row
      ? { courseId: row.courseId, topicId: row.topicId, difficulty, gradeLevel }
      : gradeLevel
        ? { gradeLevel }
        : {};
    this.router.navigate(['/app/ai/generate'], { queryParams });
  }

  protected goToBank(): void {
    this.router.navigate(['/app/bank']);
  }

  protected lockReason(): string {
    const { current, total } = this.store.progress();
    return `Disponible cuando completes las ${total}, faltan ${total - current}`;
  }

  protected onGenerateVersions(): void {
    if (!this.store.allSatisfiable() || this.generating()) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.generating.set(true);
    this.generateError.set(null);

    const blueprint: CreateExamBlueprintRow[] = this.store.requestedCells().map((key) => {
      const { courseId, topicId, difficulty } = parseCellKey(key);
      return { courseId, topicId, difficulty, count: this.store.requested().get(key) ?? 0 };
    });

    const title = `Examen ${GRADE_LEVEL_LABELS[gradeLevel]} — ${new Date().toLocaleDateString('es-PE')}`;

    this.examsService
      .createExam({ title, gradeLevel, blueprint })
      .pipe(
        switchMap((created) =>
          this.examVersionsService
            .generateVersions(created.id, DEFAULT_VERSION_COUNT)
            .pipe(map(() => created)),
        ),
      )
      .subscribe({
        next: (created) => {
          this.generating.set(false);
          this.router.navigate(['/app/exams', created.id, 'versions']);
        },
        error: () => {
          this.generating.set(false);
          this.generateError.set('No se pudo generar el examen. Inténtalo de nuevo.');
        },
      });
  }
}
