import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { map, switchMap } from 'rxjs';
import { Difficulty } from '@exams-generator/shared';
import {
  LucideAngularModule,
  Sparkles,
  TriangleAlert,
  Lock,
  Inbox,
  ChevronDown,
  ChevronRight,
  Check,
} from 'lucide-angular';
import { ButtonComponent } from '../../../ui/button/button.component';
import { CardComponent } from '../../../ui/card/card.component';
import { EmptyStateComponent } from '../../../ui/empty-state/empty-state.component';
import { InputComponent } from '../../../ui/input/input.component';
import { ProgressComponent } from '../../../ui/progress/progress.component';
import { SelectComponent } from '../../../ui/select/select.component';
import { TableComponent } from '../../../ui/table/table.component';
import { TaxonomyService } from '../../taxonomy/taxonomy.service';
import { Course, Topic } from '../../taxonomy/taxonomy.models';
import { ExamVersionsService } from '../../exam-versions/exam-versions.service';
import { ExamsService } from '../exams.service';
import {
  CreateExamBlueprintRow,
  ExamType,
  GRADE_LEVELS,
  GRADE_LEVEL_LABELS,
  GradeLevel,
  ResolveBlueprintPayload,
  ResolvedBlueprintRow,
  StockBatchCellPayload,
  Track,
  University,
} from '../exams.models';
import {
  CellKey,
  CellStatus,
  ContentRow,
  ExamBuilderStore,
  ResolvedTemplateRow,
  buildCellKey,
} from './exam-builder.store';
import { RowGroup, groupRowsByCourse } from './group-rows-by-course';
import { GridCellContentComponent } from './grid-cell-content.component';

/** "Forma A/B" — the default number of versions generated by "Generar versiones" from this screen (design doc §5). */
const DEFAULT_VERSION_COUNT = 2;

const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  [Difficulty.Easy]: 'Fácil',
  [Difficulty.Medium]: 'Media',
  [Difficulty.Hard]: 'Difícil',
};

/**
 * Grade level used to fetch `templateCourses()` — the course catalog behind
 * BOTH the "Cargar plantilla" course-name lookup (`courseNameFor`, any
 * non-manual exam type) and the `courseScope: 'selected'` checkbox list
 * (`fastest`). Every university/track template in this feature only ever
 * references `stage: 'preuniversitario'` courses (design doc + seed data) —
 * `'pre'` is the corresponding `GradeLevel` (see `stageForGrade` in
 * `exams.models.ts`). Fetching unfiltered (`getCourses()` with no args) pulls
 * every stage's catalog at once — primaria/colegio/preuniversitario course
 * names duplicated three times over.
 */
const TEMPLATE_GRADE_LEVEL: GradeLevel = 'pre';

function parseCellKey(key: CellKey): { courseId: string; topicId: string; difficulty: Difficulty } {
  const [courseId, topicId, difficulty] = key.split(':') as [string, string, Difficulty];
  return { courseId, topicId, difficulty };
}

/**
 * Converts a `ContentRow`/`CellKey`'s sentinel whole-course `topicId` (the
 * empty string `''` — see `WHOLE_COURSE_TOPIC_ID` in `exam-builder.store.ts`)
 * into the value the API expects for "match the whole course": an OMITTED
 * field, i.e. `undefined`, never a literal empty string. `blueprint-selector.ts`
 * on the backend treats `topicId !== undefined` as "match this exact topic",
 * so `topicId: ''` would try to match a topic literally named `""` and
 * silently select/count nothing — the same is true of `POST
 * /exams/stock/batch`'s `countStock()` (`cell.topicId === undefined` is what
 * triggers "sum across every topic of the course").
 *
 * ONE shared helper for BOTH places in this component that turn a store-shaped
 * (sentinel-using) `topicId` into an API-shaped one — `toCreateExamBlueprintRow`
 * (below) and `loadStock()` — so they can't drift apart again.
 */
export function toApiTopicId(topicId: string): string | undefined {
  return topicId ? topicId : undefined;
}

/**
 * Converts one grid cell into a `POST /exams` blueprint row.
 *
 * **Sentinel round-trip (design doc §3.11)**: `ExamBuilderStore.bulkLoadFromBlueprint`
 * represents a resolved whole-course row (no `topicId` — e.g. every UNCP row,
 * which has no syllabus/week data) as a `ContentRow` with the sentinel
 * `topicId: ''`, so `parseCellKey` yields `topicId === ''` for that row's
 * cells. That sentinel must NEVER reach the API as a literal empty string —
 * see `toApiTopicId`. Omitting `topicId` entirely is what already means
 * "match the whole course" for a manually-built whole-course row today
 * (`CreateExamBlueprintRow.topicId` is optional) — this is the existing
 * case, not a new one.
 *
 * Exported so the round-trip can be unit-tested directly, independent of the
 * "Generar versiones" stock-satisfiability gate (a freshly-merged template
 * row has no stock-batch result yet, so it can't be driven through that full
 * DOM flow — see exam-builder.component.spec.ts).
 */
export function toCreateExamBlueprintRow(key: CellKey, count: number): CreateExamBlueprintRow {
  const { courseId, topicId, difficulty } = parseCellKey(key);
  const apiTopicId = toApiTopicId(topicId);
  return {
    courseId,
    ...(apiTopicId !== undefined ? { topicId: apiTopicId } : {}),
    difficulty,
    count,
  };
}

/** Toggle a course id's membership in the collapsed set (immutable copy — signal-friendly). */
function toggleInSet(current: ReadonlySet<string>, id: string): ReadonlySet<string> {
  const next = new Set(current);
  if (next.has(id)) {
    next.delete(id);
  } else {
    next.add(id);
  }
  return next;
}

/**
 * Master "tabla + preview vivo" exam-builder screen (design doc §5,
 * DECISION FE-5). Replaces `ExamCreateComponent` at `/app/exams`.
 *
 * The content grid auto-populates from the tenant's full course x topic
 * catalog (`TaxonomyService`) for the selected grade level — no manual
 * "add row" step, matching the design doc's fixed matrix. `ExamBuilderStore`
 * is provided HERE (component-scoped, not root) so state resets whenever
 * the user navigates away and back (DECISION FE-5).
 */
@Component({
  selector: 'app-exam-builder',
  standalone: true,
  // `<lucide-icon>` is used directly in this component's own template
  // (sparkles/triangle-alert/lock) AND inside the nested `ui-empty-state`
  // (inbox), so the bare module goes in `imports` (selector resolution) and
  // the icon providers go in `providers` — `.pick()`'s `ModuleWithProviders`
  // cannot go in `imports` (NG2012).
  imports: [
    ButtonComponent,
    CardComponent,
    EmptyStateComponent,
    InputComponent,
    LucideAngularModule,
    ProgressComponent,
    SelectComponent,
    TableComponent,
    GridCellContentComponent,
  ],
  providers: [
    ExamBuilderStore,
    // `ui-select` (Grado) needs Check too — this component-level `.pick()`
    // shadows the root `app.config.ts` registration for its own subtree.
    LucideAngularModule.pick({ Sparkles, TriangleAlert, Lock, Inbox, ChevronDown, ChevronRight, Check })
      .providers ?? [],
  ],
  templateUrl: './exam-builder.component.html',
})
export class ExamBuilderComponent implements OnInit {
  private readonly taxonomyService = inject(TaxonomyService);
  private readonly examsService = inject(ExamsService);
  private readonly examVersionsService = inject(ExamVersionsService);
  private readonly router = inject(Router);

  protected readonly store = inject(ExamBuilderStore);

  protected readonly difficulties: readonly Difficulty[] = [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard];
  protected readonly difficultyLabels = DIFFICULTY_LABELS;
  protected readonly gradeLevelOptions = GRADE_LEVELS.map((gradeLevel) => ({
    value: gradeLevel,
    label: GRADE_LEVEL_LABELS[gradeLevel],
  }));
  /** Label shown by the read-only derived-grade indicator (template) for every non-manual exam type — see `TEMPLATE_GRADE_LEVEL`. */
  protected readonly templateGradeLevelLabel = GRADE_LEVEL_LABELS[TEMPLATE_GRADE_LEVEL];

  protected readonly selectedGradeLevel = signal<GradeLevel | null>(null);
  private readonly courses = signal<Course[]>([]);

  // --- "Tipo de examen" (design doc §3.11) ---------------------------------

  /** Defaults to `'manual'` — selecting/keeping it is the EB-T invariant: the grid below stays byte-identical to today. */
  protected readonly selectedExamTypeCode = signal<string>('manual');
  protected readonly examTypes = signal<readonly ExamType[]>([]);
  protected readonly universities = signal<readonly University[]>([]);
  protected readonly selectedUniversityId = signal<string | null>(null);
  protected readonly tracks = signal<readonly Track[]>([]);
  protected readonly selectedTrackId = signal<string | null>(null);
  /** Course catalog for the `courseScope === 'selected'` multi-select (`fastest`) — fetched separately from `courses` (which is grade-level-scoped and may not be loaded yet). */
  protected readonly templateCourses = signal<readonly Course[]>([]);
  protected readonly selectedCourseIds = signal<ReadonlySet<string>>(new Set());

  protected readonly loadingTemplate = signal(false);
  protected readonly templateError = signal<string | null>(null);
  /** Raw text of the optional "Cantidad total de preguntas" field — only needed when a university (e.g. UNI) publishes point totals but no per-course question count (`totalQuestionsOverride`). */
  protected readonly templateTotalQuestions = signal<string>('');

  protected readonly examTypeOptions = computed(() =>
    this.examTypes().map((type) => ({ value: type.code, label: type.label })),
  );
  protected readonly universityOptions = computed(() =>
    this.universities().map((university) => ({ value: university.id, label: university.name })),
  );
  /**
   * `kind: 'area'` tracks (UNCP's I-V) show "Área {code} — {name}" — docentes
   * y personal del sector reconocen el área por su número romano antes que
   * por el nombre largo. `kind: 'cycle_track'` (UNI's Básico/Preuniversitario/
   * Intensivo) has no such convention, so its `name` renders as-is.
   */
  protected readonly trackOptions = computed(() =>
    this.tracks().map((track) => ({
      value: track.id,
      label: track.kind === 'area' ? `Área ${track.code} — ${track.name}` : track.name,
    })),
  );

  protected readonly selectedExamType = computed<ExamType | null>(
    () => this.examTypes().find((type) => type.code === this.selectedExamTypeCode()) ?? null,
  );
  protected readonly isManual = computed(() => this.selectedExamTypeCode() === 'manual');
  protected readonly showCourseMultiSelect = computed(() => this.selectedExamType()?.courseScope === 'selected');
  protected readonly canLoadTemplate = computed(() => !this.isManual() && this.selectedUniversityId() !== null);

  ngOnInit(): void {
    this.examsService.getExamTypes().subscribe({
      next: (types) => this.examTypes.set(types),
      error: () => this.templateError.set('No se pudieron cargar los tipos de examen.'),
    });
  }

  protected onExamTypeChange(code: string | null): void {
    this.selectedExamTypeCode.set(code ?? 'manual');
    this.selectedUniversityId.set(null);
    this.selectedTrackId.set(null);
    this.tracks.set([]);
    this.selectedCourseIds.set(new Set());
    this.templateError.set(null);
    this.templateTotalQuestions.set('');

    if (!code || code === 'manual') {
      // EB-T invariant: manual starts fresh every time — grade level goes
      // back to being the user's own manual choice, not the derived 'pre' a
      // non-manual exam type may have left behind.
      this.selectedGradeLevel.set(null);
      return;
    }

    // Grade level is DERIVED for every non-manual exam type, never an
    // independent choice — every university/track template in this feature
    // (UNI, UNCP) is seeded under stage: 'preuniversitario' only, so there is
    // no other grade a template-driven exam could ever apply to (see
    // `TEMPLATE_GRADE_LEVEL`). Reuses `onGradeLevelChange` itself (not a
    // duplicate of its logic) so this pre-warms the preuniversitario
    // catalog+stock grid immediately — ready by the time the user picks a
    // university/track and clicks "Cargar plantilla". Guarded to skip when
    // already at `TEMPLATE_GRADE_LEVEL` (e.g. switching between two
    // non-manual exam types) so it never uselessly rebuilds the grid.
    if (this.selectedGradeLevel() !== TEMPLATE_GRADE_LEVEL) {
      this.onGradeLevelChange(TEMPLATE_GRADE_LEVEL);
    }

    if (this.universities().length === 0) {
      this.examsService.getUniversities().subscribe({
        next: (list) => this.universities.set(list),
        error: () => this.templateError.set('No se pudieron cargar las universidades.'),
      });
    }
    // Fetched for EVERY non-manual exam type, regardless of `courseScope` —
    // `courseNameFor()` needs it as a name-lookup fallback for `courseScope:
    // 'all'` types too (eta/eta_by_week), not just to populate the
    // `courseScope: 'selected'` checkbox list (Bug 1). The checkbox UI
    // itself stays gated to `courseScope === 'selected'` via
    // `showCourseMultiSelect()` in the template — only this catalog fetch is
    // unconditional.
    if (this.templateCourses().length === 0) {
      this.taxonomyService.getCourses(TEMPLATE_GRADE_LEVEL).subscribe({
        next: (list) => this.templateCourses.set(list),
        error: () => this.templateError.set('No se pudieron cargar los cursos.'),
      });
    }
  }

  protected onUniversityChange(universityId: string | null): void {
    this.selectedUniversityId.set(universityId);
    this.selectedTrackId.set(null);
    this.tracks.set([]);
    if (!universityId) {
      return;
    }
    this.examsService.getUniversityTracks(universityId).subscribe({
      next: (list) => {
        this.tracks.set(list);
        // No track step for this university — selection is already
        // complete, so load the template right away instead of waiting
        // for a manual "Cargar plantilla" click.
        // Guard against stale responses: only auto-load if this response still
        // corresponds to the currently-selected university.
        if (list.length === 0 && this.selectedUniversityId() === universityId) {
          this.loadTemplate();
        }
      },
      error: () => this.templateError.set('No se pudieron cargar los tracks.'),
    });
  }

  protected onTrackChange(trackId: string | null): void {
    this.selectedTrackId.set(trackId);
    // Clearing the track (trackId === null) leaves the selection
    // incomplete for a university that has tracks — only an actual
    // pick auto-loads.
    if (trackId) {
      this.loadTemplate();
    }
  }

  protected isCourseSelected(courseId: string): boolean {
    return this.selectedCourseIds().has(courseId);
  }

  protected toggleCourseSelection(courseId: string): void {
    this.selectedCourseIds.update((current) => toggleInSet(current, courseId));
    if (this.canLoadTemplate()) {
      this.loadTemplate();
    }
  }

  protected onTemplateTotalQuestionsChange(value: string): void {
    this.templateTotalQuestions.set(value);
  }

  /**
   * `POST /exams/blueprint/resolve` (design doc §3.11) — on success, merges
   * the returned rows into `ExamBuilderStore` as a starting point the user
   * can still edit (never locks the grid). On a 404 (no template/cycle
   * configured for this university/track yet) shows a clear inline message
   * instead of crashing or leaving the grid silently empty with no
   * explanation. On a 400 (a UNI-style template whose rows have no
   * per-course `questionCount` — only point totals — and no
   * `totalQuestionsOverride` was supplied) shows a message distinct from the
   * 404 one, guiding the user to fill in the "Cantidad total de preguntas"
   * field above.
   */
  protected loadTemplate(): void {
    const examType = this.selectedExamType();
    const universityId = this.selectedUniversityId();
    if (!examType || examType.code === 'manual' || !universityId) {
      return;
    }

    this.loadingTemplate.set(true);
    this.templateError.set(null);

    const trackId = this.selectedTrackId();
    const totalQuestionsRaw = this.templateTotalQuestions().trim();
    const payload: ResolveBlueprintPayload = {
      examTypeCode: examType.code,
      universityId,
      ...(trackId ? { trackId } : {}),
      ...(examType.courseScope === 'selected' ? { selectedCourseIds: Array.from(this.selectedCourseIds()) } : {}),
      ...(totalQuestionsRaw ? { totalQuestionsOverride: Number(totalQuestionsRaw) } : {}),
    };

    this.examsService.resolveBlueprint(payload).subscribe({
      next: (result) => {
        this.loadingTemplate.set(false);
        this.mergeResolvedBlueprint(result.blueprint);
      },
      error: (error: HttpErrorResponse) => {
        this.loadingTemplate.set(false);
        this.templateError.set(
          error.status === 404
            ? 'No hay una plantilla configurada para esta universidad/track todavía.'
            : error.status === 400
              ? ((error.error?.message as string | undefined) ??
                'Esta plantilla requiere que indiques la cantidad total de preguntas — complétala e intenta de nuevo.')
              : 'No se pudo cargar la plantilla. Inténtalo de nuevo.',
        );
      },
    });
  }

  /**
   * Resolves display names for each `BlueprintRow` (the resolve endpoint
   * only returns ids) before handing them to `store.bulkLoadFromBlueprint` —
   * the store never fetches taxonomy data itself, same separation the
   * manual grid already keeps (`loadTopicsAndStock` resolves names in the
   * component, `addRow` just stores them). Looks first at the loaded
   * grade-level course catalog, then the course multi-select catalog, then
   * any row already in the grid, and falls back to the raw id as a last
   * resort (only reachable if a template references a course none of those
   * catalogs have loaded yet).
   */
  private mergeResolvedBlueprint(rows: readonly ResolvedBlueprintRow[]): void {
    const resolved: ResolvedTemplateRow[] = rows.map((row) => ({
      courseId: row.courseId,
      courseName: this.courseNameFor(row.courseId),
      topicId: row.topicId,
      topicName: row.topicId ? this.topicNameFor(row.courseId, row.topicId) : undefined,
      count: row.count,
      difficulty: row.difficulty,
    }));
    this.store.bulkLoadFromBlueprint(resolved);

    // Bug 3(b): if a grade level was already selected (its own `buildGrid()`
    // -> `loadStock()` chain already ran), newly-merged template rows have
    // no stock fetched yet — nothing else triggers one for them. Re-run
    // `loadStock()`; it iterates `this.store.rows()` fresh each call, so it
    // naturally covers every row (old and newly-merged) without duplicating
    // rows or requested counts.
    const gradeLevel = this.selectedGradeLevel();
    if (gradeLevel) {
      this.loadStock(gradeLevel);
    }
  }

  private courseNameFor(courseId: string): string {
    return (
      this.courses().find((course) => course.id === courseId)?.name ??
      this.templateCourses().find((course) => course.id === courseId)?.name ??
      this.store.rows().find((row) => row.courseId === courseId)?.courseName ??
      courseId
    );
  }

  private topicNameFor(courseId: string, topicId: string): string {
    return (
      this.store.rows().find((row) => row.courseId === courseId && row.topicId === topicId)?.topicName ?? topicId
    );
  }

  protected readonly loading = signal(false);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly emptyBank = signal(false);

  protected readonly loadingPreview = signal(false);
  protected readonly previewError = signal<string | null>(null);

  protected readonly generating = signal(false);
  protected readonly generateError = signal<string | null>(null);

  /** Rows grouped by course, for the "read like the tree" course subheading (design doc §5.1). */
  protected readonly groupedRows = computed<readonly RowGroup[]>(() => groupRowsByCourse(this.store.rows()));

  /**
   * Courses the user has manually collapsed. Default-empty means every course
   * starts EXPANDED (the grid is a fill-in matrix — hiding rows by default would
   * bury the work). Collapse is opt-in, to fold away courses the teacher isn't
   * touching. Mirrors the bank tree's `expand/collapse` affordance (commit 50dcff5).
   */
  private readonly collapsedCourses = signal<ReadonlySet<string>>(new Set());

  protected toggleCourse(courseId: string): void {
    this.collapsedCourses.update((current) => toggleInSet(current, courseId));
  }

  protected isCourseExpanded(courseId: string): boolean {
    return !this.collapsedCourses().has(courseId);
  }

  protected expandAll(): void {
    this.collapsedCourses.set(new Set());
  }

  protected collapseAll(): void {
    this.collapsedCourses.set(new Set(this.groupedRows().map((group) => group.courseId)));
  }

  protected chevronFor(expanded: boolean): string {
    return expanded ? 'chevron-down' : 'chevron-right';
  }

  protected onGradeLevelChange(gradeLevel: GradeLevel | null): void {
    this.selectedGradeLevel.set(gradeLevel);
    if (!gradeLevel) {
      return;
    }
    this.buildGrid(gradeLevel);
  }

  protected retry(): void {
    const gradeLevel = this.selectedGradeLevel();
    if (gradeLevel) {
      this.buildGrid(gradeLevel);
    }
  }

  private buildGrid(gradeLevel: GradeLevel): void {
    this.loading.set(true);
    this.errorMessage.set(null);
    this.emptyBank.set(false);
    this.store.setGradeLevel(gradeLevel);

    this.taxonomyService.getCourses(gradeLevel).subscribe({
      next: (courses) => {
        this.courses.set(courses);
        if (courses.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }
        this.loadTopicsAndStock(gradeLevel, courses);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  /**
   * Batched sibling of the per-course `forkJoin` fan-out this used to do —
   * fetches every course's topics in ONE `getTopicsForCourses()` request
   * (fixes the N+1 that used to trip the global ThrottlerGuard), then groups
   * the flat response back by `courseId` (preserving `courses`' original
   * order) so each row still gets added in the same course-then-topic order
   * as before.
   */
  private loadTopicsAndStock(gradeLevel: GradeLevel, courses: readonly Course[]): void {
    this.taxonomyService.getTopicsForCourses(courses.map((course) => course.id), gradeLevel).subscribe({
      next: (topics) => {
        if (topics.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }

        const topicsByCourseId = new Map<string, Topic[]>();
        for (const topic of topics) {
          const bucket = topicsByCourseId.get(topic.courseId);
          if (bucket) {
            bucket.push(topic);
          } else {
            topicsByCourseId.set(topic.courseId, [topic]);
          }
        }

        for (const course of courses) {
          for (const topic of topicsByCourseId.get(course.id) ?? []) {
            this.store.addRow({
              id: `${course.id}:${topic.id}`,
              courseId: course.id,
              courseName: course.name,
              topicId: topic.id,
              topicName: topic.name,
            });
          }
        }
        this.loadStock(gradeLevel);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  private loadStock(gradeLevel: GradeLevel): void {
    const cells: StockBatchCellPayload[] = [];
    for (const row of this.store.rows()) {
      for (const difficulty of this.difficulties) {
        // Bug 3(a): `row.topicId` is the store's sentinel `''` for a
        // whole-course row — translate it to an omitted field via
        // `toApiTopicId` (same helper `toCreateExamBlueprintRow` uses),
        // never send a literal empty string. `ExamBuilderStore.setStockResults`
        // does the matching reverse translation on the response.
        cells.push({ courseId: row.courseId, topicId: toApiTopicId(row.topicId), difficulty });
      }
    }

    this.examsService.stockBatch({ gradeLevel, cells }).subscribe({
      next: (result) => {
        this.store.setStockResults(result.results);
        this.loading.set(false);
        const total = result.results.reduce((sum, cell) => sum + cell.available, 0);
        this.emptyBank.set(total === 0);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  protected cellKey(row: ContentRow, difficulty: Difficulty): CellKey {
    return buildCellKey(row.courseId, row.topicId, difficulty);
  }

  protected stockFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.stock().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.requested().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedStrFor(row: ContentRow, difficulty: Difficulty): string {
    const value = this.requestedFor(row, difficulty);
    return value > 0 ? String(value) : '';
  }

  protected previewFor(row: ContentRow, difficulty: Difficulty): readonly string[] {
    return this.store.previewCache().get(this.cellKey(row, difficulty)) ?? [];
  }

  protected statusFor(row: ContentRow, difficulty: Difficulty): CellStatus {
    return this.store.cellStatus(this.cellKey(row, difficulty));
  }

  /** Cell wrapper classes — shortage cells get an unmissable warning-stock tint + border (improvement 3). */
  protected cellClasses(row: ContentRow, difficulty: Difficulty): string {
    const base = 'px-3 py-2 align-top transition-colors';
    return this.statusFor(row, difficulty) === 'short'
      ? `${base} rounded-field border border-warn-text bg-warn-bg`
      : base;
  }

  /** Muted (not alarming) styling for an untouched zero-stock "de 0" label vs. the normal "de N" (improvement 4). */
  protected stockOkClasses(row: ContentRow, difficulty: Difficulty): string {
    return this.stockFor(row, difficulty) === 0 ? 'text-sm text-n400' : 'text-sm text-n600';
  }

  /** Per-difficulty column total for the totals row/footer (improvement 2). */
  protected totalFor(difficulty: Difficulty): number {
    return this.store.totalsByDifficulty().get(difficulty) ?? 0;
  }

  /** Grand total across every requested cell (improvement 2). */
  protected grandTotalValue(): number {
    return this.store.grandTotal();
  }

  protected onRequestedChange(row: ContentRow, difficulty: Difficulty, rawValue: string): void {
    const key = this.cellKey(row, difficulty);
    const count = Math.max(0, Number(rawValue) || 0);
    this.store.setRequested(key, count);
    if (count <= 0) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.loadingPreview.set(true);
    this.previewError.set(null);

    this.examsService
      .previewExam({
        gradeLevel,
        blueprint: [{ courseId: row.courseId, topicId: row.topicId, difficulty, count }],
      })
      .subscribe({
        next: (result) => {
          this.loadingPreview.set(false);
          const questionIds = result.selections[0]?.questionIds ?? [];
          this.store.mergePreview(key, questionIds);
        },
        error: () => {
          this.loadingPreview.set(false);
          this.previewError.set('No se pudo cargar la vista previa. Inténtalo de nuevo.');
        },
      });
  }

  protected lowerToStock(row: ContentRow, difficulty: Difficulty): void {
    const stock = this.stockFor(row, difficulty);
    this.onRequestedChange(row, difficulty, String(stock));
  }

  protected goToUpload(): void {
    // The legacy raw-HTML /app/bank/upload screen was removed (audit P1) —
    // /app/bank/new is the only design-system question intake now.
    this.router.navigate(['/app/bank/new']);
  }

  /**
   * Bridge to the AI generator. When launched from a specific shortage cell we
   * carry its curso·tema·dificultad·grado as query params so the generator opens
   * pre-filled — the teacher shouldn't re-pick what they already chose here. From
   * the empty-state button (no row) we still carry the selected grade.
   */
  protected goToAiGenerate(row?: ContentRow, difficulty?: Difficulty): void {
    const gradeLevel = this.selectedGradeLevel();
    const queryParams = row
      ? { courseId: row.courseId, topicId: row.topicId, difficulty, gradeLevel }
      : gradeLevel
        ? { gradeLevel }
        : {};
    this.router.navigate(['/app/ai/generate'], { queryParams });
  }

  protected goToBank(): void {
    this.router.navigate(['/app/bank']);
  }

  protected lockReason(): string {
    const { current, total } = this.store.progress();
    return `Disponible cuando completes las ${total}, faltan ${total - current}`;
  }

  protected onGenerateVersions(): void {
    if (!this.store.allSatisfiable() || this.generating()) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.generating.set(true);
    this.generateError.set(null);

    const blueprint: CreateExamBlueprintRow[] = this.store
      .requestedCells()
      .map((key) => toCreateExamBlueprintRow(key, this.store.requested().get(key) ?? 0));

    const title = `Examen ${GRADE_LEVEL_LABELS[gradeLevel]} — ${new Date().toLocaleDateString('es-PE')}`;

    // `generateVersions` ENQUEUES generation and resolves on the 202 — the
    // PDFs are compiled by a backend worker (audit P0). So this navigates as
    // soon as the job is accepted instead of blocking the builder for the
    // whole compile; the versions screen picks the job up and renders its
    // live progress. An error here is still a real synchronous rejection
    // (the exam was created but the request was refused before enqueue).
    this.examsService
      .createExam({ title, gradeLevel, blueprint })
      .pipe(
        switchMap((created) =>
          this.examVersionsService
            .generateVersions(created.id, DEFAULT_VERSION_COUNT)
            .pipe(map(() => created)),
        ),
      )
      .subscribe({
        next: (created) => {
          this.generating.set(false);
          this.router.navigate(['/app/exams', created.id, 'versions']);
        },
        error: () => {
          this.generating.set(false);
          this.generateError.set('No se pudo generar el examen. Inténtalo de nuevo.');
        },
      });
  }
}
