import { Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { forkJoin, map, switchMap } from 'rxjs';
import { Difficulty } from '@exams-generator/shared';
import { ButtonComponent } from '../../../ui/button/button.component';
import { CardComponent } from '../../../ui/card/card.component';
import { EmptyStateComponent } from '../../../ui/empty-state/empty-state.component';
import { InputComponent } from '../../../ui/input/input.component';
import { ProgressComponent } from '../../../ui/progress/progress.component';
import { SelectComponent } from '../../../ui/select/select.component';
import { TableComponent } from '../../../ui/table/table.component';
import { TagComponent } from '../../../ui/tag/tag.component';
import { TaxonomyService } from '../../taxonomy/taxonomy.service';
import { Course } from '../../taxonomy/taxonomy.models';
import { ExamVersionsService } from '../../exam-versions/exam-versions.service';
import { ExamsService } from '../exams.service';
import {
  CreateExamBlueprintRow,
  GRADE_LEVELS,
  GRADE_LEVEL_LABELS,
  GradeLevel,
  StockBatchCellPayload,
} from '../exams.models';
import { CellKey, CellStatus, ContentRow, ExamBuilderStore, buildCellKey } from './exam-builder.store';

/** "Forma A/B" — the default number of versions generated by "Generar versiones" from this screen (design doc §5). */
const DEFAULT_VERSION_COUNT = 2;

const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  [Difficulty.Easy]: 'Fácil',
  [Difficulty.Medium]: 'Media',
  [Difficulty.Hard]: 'Difícil',
};

function parseCellKey(key: CellKey): { courseId: string; topicId: string; difficulty: Difficulty } {
  const [courseId, topicId, difficulty] = key.split(':') as [string, string, Difficulty];
  return { courseId, topicId, difficulty };
}

/**
 * Master "tabla + preview vivo" exam-builder screen (design doc §5,
 * DECISION FE-5). Replaces `ExamCreateComponent` at `/app/exams`.
 *
 * The content grid auto-populates from the tenant's full course x topic
 * catalog (`TaxonomyService`) for the selected grade level — no manual
 * "add row" step, matching the design doc's fixed matrix. `ExamBuilderStore`
 * is provided HERE (component-scoped, not root) so state resets whenever
 * the user navigates away and back (DECISION FE-5).
 */
@Component({
  selector: 'app-exam-builder',
  standalone: true,
  imports: [
    ButtonComponent,
    CardComponent,
    EmptyStateComponent,
    InputComponent,
    ProgressComponent,
    SelectComponent,
    TableComponent,
    TagComponent,
  ],
  providers: [ExamBuilderStore],
  templateUrl: './exam-builder.component.html',
})
export class ExamBuilderComponent {
  private readonly taxonomyService = inject(TaxonomyService);
  private readonly examsService = inject(ExamsService);
  private readonly examVersionsService = inject(ExamVersionsService);
  private readonly router = inject(Router);

  protected readonly store = inject(ExamBuilderStore);

  protected readonly difficulties: readonly Difficulty[] = [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard];
  protected readonly difficultyLabels = DIFFICULTY_LABELS;
  protected readonly gradeLevelOptions = GRADE_LEVELS.map((gradeLevel) => ({
    value: gradeLevel,
    label: GRADE_LEVEL_LABELS[gradeLevel],
  }));

  protected readonly selectedGradeLevel = signal<GradeLevel | null>(null);
  private readonly courses = signal<Course[]>([]);

  protected readonly loading = signal(false);
  protected readonly errorMessage = signal<string | null>(null);
  protected readonly emptyBank = signal(false);

  protected readonly loadingPreview = signal(false);
  protected readonly previewError = signal<string | null>(null);

  protected readonly generating = signal(false);
  protected readonly generateError = signal<string | null>(null);

  protected onGradeLevelChange(gradeLevel: GradeLevel | null): void {
    this.selectedGradeLevel.set(gradeLevel);
    if (!gradeLevel) {
      return;
    }
    this.buildGrid(gradeLevel);
  }

  private buildGrid(gradeLevel: GradeLevel): void {
    this.loading.set(true);
    this.errorMessage.set(null);
    this.emptyBank.set(false);
    this.store.setGradeLevel(gradeLevel);

    this.taxonomyService.getCourses().subscribe({
      next: (courses) => {
        this.courses.set(courses);
        if (courses.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }
        this.loadTopicsAndStock(gradeLevel, courses);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  private loadTopicsAndStock(gradeLevel: GradeLevel, courses: readonly Course[]): void {
    forkJoin(
      courses.map((course) =>
        this.taxonomyService
          .getTopics(course.id)
          .pipe(map((topics) => topics.map((topic) => ({ course, topic })))),
      ),
    ).subscribe({
      next: (grouped) => {
        const pairs = grouped.flat();
        if (pairs.length === 0) {
          this.loading.set(false);
          this.emptyBank.set(true);
          return;
        }
        for (const { course, topic } of pairs) {
          this.store.addRow({
            id: `${course.id}:${topic.id}`,
            courseId: course.id,
            courseName: course.name,
            topicId: topic.id,
            topicName: topic.name,
          });
        }
        this.loadStock(gradeLevel);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  private loadStock(gradeLevel: GradeLevel): void {
    const cells: StockBatchCellPayload[] = [];
    for (const row of this.store.rows()) {
      for (const difficulty of this.difficulties) {
        cells.push({ courseId: row.courseId, topicId: row.topicId, difficulty });
      }
    }

    this.examsService.stockBatch({ gradeLevel, cells }).subscribe({
      next: (result) => {
        this.store.setStockResults(result.results);
        this.loading.set(false);
        const total = result.results.reduce((sum, cell) => sum + cell.available, 0);
        this.emptyBank.set(total === 0);
      },
      error: () => {
        this.loading.set(false);
        this.errorMessage.set('No se pudieron cargar las existencias. Inténtalo de nuevo.');
      },
    });
  }

  protected cellKey(row: ContentRow, difficulty: Difficulty): CellKey {
    return buildCellKey(row.courseId, row.topicId, difficulty);
  }

  protected stockFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.stock().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedFor(row: ContentRow, difficulty: Difficulty): number {
    return this.store.requested().get(this.cellKey(row, difficulty)) ?? 0;
  }

  protected requestedStrFor(row: ContentRow, difficulty: Difficulty): string {
    const value = this.requestedFor(row, difficulty);
    return value > 0 ? String(value) : '';
  }

  protected previewFor(row: ContentRow, difficulty: Difficulty): readonly string[] {
    return this.store.previewCache().get(this.cellKey(row, difficulty)) ?? [];
  }

  protected statusFor(row: ContentRow, difficulty: Difficulty): CellStatus {
    return this.store.cellStatus(this.cellKey(row, difficulty));
  }

  protected onRequestedChange(row: ContentRow, difficulty: Difficulty, rawValue: string): void {
    const key = this.cellKey(row, difficulty);
    const count = Number(rawValue) || 0;
    this.store.setRequested(key, count);
    if (count <= 0) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.loadingPreview.set(true);
    this.previewError.set(null);

    this.examsService
      .previewExam({
        gradeLevel,
        blueprint: [{ courseId: row.courseId, topicId: row.topicId, difficulty, count }],
      })
      .subscribe({
        next: (result) => {
          this.loadingPreview.set(false);
          const questionIds = result.selections[0]?.questionIds ?? [];
          this.store.mergePreview(key, questionIds);
        },
        error: () => {
          this.loadingPreview.set(false);
          this.previewError.set('No se pudo cargar la vista previa. Inténtalo de nuevo.');
        },
      });
  }

  protected lowerToStock(row: ContentRow, difficulty: Difficulty): void {
    const stock = this.stockFor(row, difficulty);
    this.onRequestedChange(row, difficulty, String(stock));
  }

  protected goToUpload(): void {
    this.router.navigate(['/app/bank/upload']);
  }

  protected goToAiGenerate(row?: ContentRow, difficulty?: Difficulty): void {
    void row;
    void difficulty;
    this.router.navigate(['/app/ai/generate']);
  }

  protected goToBank(): void {
    this.router.navigate(['/app/bank']);
  }

  protected lockReason(): string {
    const { current, total } = this.store.progress();
    return `Disponible cuando completes las ${total}, faltan ${total - current}`;
  }

  protected onGenerateVersions(): void {
    if (!this.store.allSatisfiable() || this.generating()) {
      return;
    }

    const gradeLevel = this.selectedGradeLevel();
    if (!gradeLevel) {
      return;
    }

    this.generating.set(true);
    this.generateError.set(null);

    const blueprint: CreateExamBlueprintRow[] = this.store.requestedCells().map((key) => {
      const { courseId, topicId, difficulty } = parseCellKey(key);
      return { courseId, topicId, difficulty, count: this.store.requested().get(key) ?? 0 };
    });

    const title = `Examen ${GRADE_LEVEL_LABELS[gradeLevel]} — ${new Date().toLocaleDateString('es-PE')}`;

    this.examsService
      .createExam({ title, gradeLevel, blueprint })
      .pipe(
        switchMap((created) =>
          this.examVersionsService
            .generateVersions(created.id, DEFAULT_VERSION_COUNT)
            .pipe(map(() => created)),
        ),
      )
      .subscribe({
        next: (created) => {
          this.generating.set(false);
          this.router.navigate(['/app/exams', created.id, 'versions']);
        },
        error: () => {
          this.generating.set(false);
          this.generateError.set('No se pudo generar el examen. Inténtalo de nuevo.');
        },
      });
  }
}
