-- 0023_topic_grades
--
-- One topic per curriculum concept; the grades it is taught at move to
-- `topic_grades` (design doc 2026-09-03-taxonomy-topic-grades-design.md,
-- audit 2026-09-03-taxonomy-data-audit.md).
--
-- Schema change AND data collapse in ONE file on purpose: prod runs
-- `migrate && seed && main` (infra/docker-compose.dokploy.yml), the drizzle
-- migrator wraps every pending migration in a single transaction
-- (drizzle-orm/pg-core/dialect.js), and there is no manual step to forget.
-- Irreversible except from the `pg_dump` taken before deploy.
--
-- Generated by `drizzle-kit generate` and then hand-edited: every DDL block
-- below is the generated one verbatim, only reordered so the data collapse
-- runs between the new table and the drop of `topics.grade_level` — the
-- collapse reads that column. `migration-snapshot.spec.ts` still passes: it
-- regenerates against `meta/0023_snapshot.json`, finds no schema drift, and so
-- compares this file against itself.

CREATE TABLE IF NOT EXISTS "topic_grades" (
	"topic_id" uuid NOT NULL,
	"grade_level" text NOT NULL,
	CONSTRAINT "topic_grades_topic_id_grade_level_pk" PRIMARY KEY("topic_id","grade_level")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "topic_grades" ADD CONSTRAINT "topic_grades_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "topic_grades" ADD CONSTRAINT "topic_grades_grade_level_grade_levels_code_fk" FOREIGN KEY ("grade_level") REFERENCES "public"."grade_levels"("code") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "topic_grades_grade_level_idx" ON "topic_grades" USING btree ("grade_level");--> statement-breakpoint

-- The canonical row of every `(course_id, name)` group: the copy whose grade
-- has the lowest `grade_levels.sort_order`, id as the tie-break. `topics` has
-- no `created_at`, so id IS the tie-break (the design doc's "created_at/id"
-- collapses to id). Grade-less rows sort last via the COALESCE sentinel.
-- TEMP + ON COMMIT DROP: the migrator holds one connection for the whole
-- transaction, and the table must not survive it.
CREATE TEMP TABLE "topic_collapse_map" ON COMMIT DROP AS
SELECT
  t."id" AS copy_id,
  first_value(t."id") OVER (
    PARTITION BY t."course_id", t."name"
    ORDER BY COALESCE(g."sort_order", 2147483647), t."id"
  ) AS canonical_id
FROM "topics" t
LEFT JOIN "grade_levels" g ON g."code" = t."grade_level";
--> statement-breakpoint
CREATE UNIQUE INDEX ON "topic_collapse_map" (copy_id);
--> statement-breakpoint

-- Every grade any copy of the group carried becomes a row on the canonical
-- topic. A topic with NULL grade contributes nothing and ends up with no rows
-- — "taught across the whole stage" (2 preuni topics today).
INSERT INTO "topic_grades" ("topic_id", "grade_level")
SELECT DISTINCT m.canonical_id, t."grade_level"
FROM "topics" t
JOIN "topic_collapse_map" m ON m.copy_id = t."id"
WHERE t."grade_level" IS NOT NULL
ON CONFLICT DO NOTHING;
--> statement-breakpoint

-- Repoint every FK to `topics.id` off the copies. `questions.grade_level` is
-- deliberately untouched: it is the question's OWN axis, not the topic's.
UPDATE "questions" q
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = q."topic_id" AND m.canonical_id <> q."topic_id";
--> statement-breakpoint
UPDATE "generation_jobs" j
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = j."topic_id" AND m.canonical_id <> j."topic_id";
--> statement-breakpoint
UPDATE "exam_blueprint_rows" r
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = r."topic_id" AND m.canonical_id <> r."topic_id";
--> statement-breakpoint
UPDATE "exam_blueprint_template_rows" r
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = r."topic_id" AND m.canonical_id <> r."topic_id";
--> statement-breakpoint

-- `subtopics` is unique by (topic_id, slug): drop the copy's row when the
-- canonical topic already owns that slug, then repoint the rest. Nothing uses
-- subtopics today (0 of 67,029 questions carry one), but the FK still blocks
-- the delete below if a row is left pointing at a copy.
DELETE FROM "subtopics" s
USING "topic_collapse_map" m, "subtopics" keep
WHERE m.copy_id = s."topic_id"
  AND m.canonical_id <> s."topic_id"
  AND keep."topic_id" = m.canonical_id
  AND keep."slug" = s."slug";
--> statement-breakpoint
UPDATE "subtopics" s
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = s."topic_id" AND m.canonical_id <> s."topic_id";
--> statement-breakpoint

-- `syllabus_week_maps` is unique by (template_id, topic_id): a copy's row is
-- redundant when the canonical topic is already mapped for that template.
DELETE FROM "syllabus_week_maps" w
USING "topic_collapse_map" m, "syllabus_week_maps" keep
WHERE m.copy_id = w."topic_id"
  AND m.canonical_id <> w."topic_id"
  AND keep."template_id" = w."template_id"
  AND keep."topic_id" = m.canonical_id;
--> statement-breakpoint
UPDATE "syllabus_week_maps" w
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = w."topic_id" AND m.canonical_id <> w."topic_id";
--> statement-breakpoint

-- Folders. Per tenant, several seeded folders can point at copies of one
-- group; the survivor is the lowest `position` (id as tie-break), and the
-- others hand it their questions and their children before being deleted.
-- `question_folders_tenant_topic_idx` (partial unique on tenant_id, topic_id)
-- is why they cannot simply be repointed.
CREATE TEMP TABLE "folder_merge_map" ON COMMIT DROP AS
SELECT
  f."id" AS loser_id,
  first_value(f."id") OVER (
    PARTITION BY f."tenant_id", m.canonical_id
    ORDER BY f."position", f."id"
  ) AS keeper_id
FROM "question_folders" f
JOIN "topic_collapse_map" m ON m.copy_id = f."topic_id";
--> statement-breakpoint
CREATE UNIQUE INDEX ON "folder_merge_map" (loser_id);
--> statement-breakpoint
UPDATE "questions" q
SET "folder_id" = fm.keeper_id
FROM "folder_merge_map" fm
WHERE fm.loser_id = q."folder_id" AND fm.keeper_id <> q."folder_id";
--> statement-breakpoint
UPDATE "question_folders" f
SET "parent_id" = fm.keeper_id
FROM "folder_merge_map" fm
WHERE fm.loser_id = f."parent_id" AND fm.keeper_id <> f."parent_id";
--> statement-breakpoint
DELETE FROM "question_folders" f
USING "folder_merge_map" fm
WHERE fm.loser_id = f."id" AND fm.keeper_id <> f."id";
--> statement-breakpoint
UPDATE "question_folders" f
SET "topic_id" = m.canonical_id
FROM "topic_collapse_map" m
WHERE m.copy_id = f."topic_id" AND m.canonical_id <> f."topic_id";
--> statement-breakpoint

-- Strip the seeded ` · <grade label>` suffix. Matched against the TOPIC's own
-- name rather than a list of the 12 labels: a folder named exactly
-- "<topic name> · <anything>" is one the seeder wrote, and a folder the
-- teacher renamed by hand never matches, so her name survives.
UPDATE "question_folders" f
SET "name" = left(t."name", 80)
FROM "topics" t
WHERE f."topic_id" = t."id"
  AND f."name" <> left(t."name", 80)
  AND starts_with(f."name", t."name" || ' · ');
--> statement-breakpoint

-- Stripping a suffix (or re-parenting a child above) can land two siblings on
-- the same name, which `question_folders_sibling_name_idx` /
-- `question_folders_root_name_idx` forbid. Same rule the seeder used to apply
-- (`dedupeSiblingNames`): first one keeps the bare name, the rest get " (2)",
-- " (3)", … clamped to 80 characters.
WITH ranked AS (
  SELECT
    "id",
    row_number() OVER (
      PARTITION BY "tenant_id", COALESCE("parent_id", '00000000-0000-0000-0000-000000000000'::uuid), "name"
      ORDER BY "position", "id"
    ) AS rn,
    "name"
  FROM "question_folders"
)
UPDATE "question_folders" f
SET "name" = left(ranked."name", 80 - length(' (' || ranked.rn || ')')) || ' (' || ranked.rn || ')'
FROM ranked
WHERE ranked."id" = f."id" AND ranked.rn > 1;
--> statement-breakpoint

-- Nothing references the copies any more.
DELETE FROM "topics" t
USING "topic_collapse_map" m
WHERE m.copy_id = t."id" AND m.canonical_id <> t."id";
--> statement-breakpoint

ALTER TABLE "topics" DROP CONSTRAINT "topics_grade_level_grade_levels_code_fk";
--> statement-breakpoint
DROP INDEX IF EXISTS "topics_course_id_name_grade_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "topics_course_id_slug_grade_idx";--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "topics_course_id_name_idx" ON "topics" USING btree ("course_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "topics_course_id_slug_idx" ON "topics" USING btree ("course_id","slug") WHERE "topics"."slug" is not null;--> statement-breakpoint
ALTER TABLE "topics" DROP COLUMN IF EXISTS "grade_level";
