import { Controller, Get, Param, ParseUUIDPipe, Res, UseGuards } from "@nestjs/common";
import { Response } from "express";
import { CurrentUser } from "../auth/current-user.decorator";
import { JwtAuthGuard } from "../auth/jwt-auth.guard";
import { AuthTokenPayload } from "../auth/token.service";
import { assetCacheControl, assetETag } from "./asset-cache";
import { pdfDownloadFilename } from "./asset-filename";
import { AssetsService } from "./assets.service";
import { isSafeImageMime } from "./image-mime";

/**
 * `GET /assets/:id` — streams the binary object behind an `assets` row
 * (the piece `GET /bank/questions`'s bare `imageAssetId` needs to be
 * actually renderable, e.g. via `<img>` on the web). Bearer-JWT protected
 * like every other route; tenant scoping happens in `AssetsService`, same
 * pattern as `BankController`.
 */
@Controller("assets")
@UseGuards(JwtAuthGuard)
export class AssetsController {
  constructor(private readonly service: AssetsService) {}

  /**
   * The bank tree's 40px leaf row, one per question for a whole page of 50 —
   * see `AssetsService.getThumbnailContent` for why only that row gets a
   * shrunk image and the readable views keep the original.
   *
   * Declared BEFORE `@Get(":id")`: a static-looking segment must be registered
   * ahead of the generic `:id` catch-all in the same file for Nest's route
   * matching to prefer it (same reason `bank.controller.ts` orders `summary`
   * and `:id/preview` the way it does).
   *
   * `immutable` applies here for the same reason it does to the original: the
   * thumbnail's storage key is derived from an original whose bytes cannot
   * change, so neither can the thumbnail's.
   */
  @Get(":id/thumb")
  async getAssetThumbnail(
    @CurrentUser() user: AuthTokenPayload,
    @Param("id", ParseUUIDPipe) id: string,
    @Res() res: Response,
  ): Promise<void> {
    const thumbnail = await this.service.getThumbnailContent(user, id);

    res.set("X-Content-Type-Options", "nosniff");
    res.set("Cache-Control", assetCacheControl(thumbnail.mime));
    res.set("ETag", assetETag(thumbnail.buffer));
    // `getThumbnailContent` only ever resolves for an asset that already
    // passed `isSafeImageMime`, and falls back to those same original bytes
    // when the resize fails — so this is always an image mime. Kept explicit
    // rather than assumed, matching the branch below.
    res.set("Content-Type", isSafeImageMime(thumbnail.mime) ? thumbnail.mime : "application/octet-stream");
    res.set("Content-Disposition", "inline");
    res.send(thumbnail.buffer);
  }

  @Get(":id")
  async getAsset(
    @CurrentUser() user: AuthTokenPayload,
    @Param("id", ParseUUIDPipe) id: string,
    @Res() res: Response,
  ): Promise<void> {
    // Resolved BEFORE any validator comparison, and deliberately so: a 304 must
    // never become a cheaper way to confirm that another tenant's asset id
    // exists. A cross-tenant request is a 404 whether or not its `If-None-Match`
    // happens to match.
    const asset = await this.service.getAssetContent(user, id);
    // Never echo an attacker-chosen Content-Type. `asset.mime` came from the
    // uploader's own header (multer copies it verbatim); an `image/svg+xml`
    // or `text/html` blob served inline runs as script in a same-tenant
    // viewer's tab — stored XSS. Collapse anything outside the allowlists
    // below to octet-stream, and forbid MIME sniffing so the browser cannot
    // second-guess us back into rendering it.
    res.set("X-Content-Type-Options", "nosniff");

    // Caching policy + validator (see `asset-cache.ts` for why images may be
    // `immutable` and PDFs may not). Both are set before `res.send()`, which is
    // what lets Express answer a matching `If-None-Match` with a bodiless 304
    // on its own — the whole point, since the web fetches every bank thumbnail
    // as a separate authenticated XHR against an origin ~620ms away
    // (docs/audit-2026-08-26-prod-latency.md §3).
    //
    // The object is still read from storage to hash it, so a 304 saves the
    // payload but not the MinIO round-trip. That is the half that costs, and
    // skipping the read would mean persisting a content hash on `assets` —
    // a schema change, and a separate decision.
    res.set("Cache-Control", assetCacheControl(asset.mime));
    res.set("ETag", assetETag(asset.buffer));

    // Exam version PDFs come through this same route
    // (`exam-generation.service.ts` links them as `/assets/:id`), and the
    // image-only branch below served them as an unnamed octet-stream — so
    // opening the URL directly saved a bare uuid with no extension. They are
    // server-generated by Typst, never uploaded, and go out as `attachment`:
    // that both names the file and keeps a PDF viewer from ever running one
    // inline.
    if (asset.mime === "application/pdf") {
      res.set("Content-Type", "application/pdf");
      res.set("Content-Disposition", `attachment; filename="${pdfDownloadFilename(asset.storageKey, id)}"`);
      res.send(asset.buffer);
      return;
    }

    res.set("Content-Type", isSafeImageMime(asset.mime) ? asset.mime : "application/octet-stream");
    res.set("Content-Disposition", "inline");
    res.send(asset.buffer);
  }
}
